version: "3.7"

services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "7001:80"
      - "7002:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
    restart: always
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./docker/php
    # монтируем директорию с проектами
    volumes:
      - ./:/var/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs:/usr/local/var/logs
    restart: always

